services:
  - type: web
    name: ArbTriBot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ADMIN_CHAT_IDS
        sync: false
      - key: BYBIT_API_KEY
        sync: false
      - key: BYBIT_API_SECRET
        sync: false
      - key: BINANCE_API_KEY
        sync: false
      - key: BINANCE_API_SECRET
        sync: false
      - key: TRADE_AMOUNT_USDT
        value: "10"
      - key: MIN_PROFIT_PERCENT
        value: "0.3"
      - key: AUTO_TRADE
        value: "false"
      - key: RENDER_EXTERNAL_URL
        value: "https://arbt-bot.onrender.com"
